//create stud _COURSE

export const CREATESTUDENT_COURSE_REQUEST = "CREATESTUDENT_COURSE_REQUEST";
export const CREATESTUDENT_COURSE_SUCCESS = "CREATESTUDENT_COURSE_SUCCESS";
export const CREATESTUDENT_COURSE_FAIL = "CREATESTUDENT_COURSE_FAIL";

//ALL stud_COURSE

export const ALLSTUDENT_COURSE_REQUEST = "ALLSTUDENT_COURSE_REQUEST";
export const ALLSTUDENT_COURSE_SUCCESS = "ALLSTUDENT_COURSE_SUCCESS";
export const ALLSTUDENT_COURSE_FAIL = "ALLSTUDENT_COURSE_FAIL";

//DELETE stud_COURSE

export const DELETESTUDENT_COURSE_REQUEST = "DELETESTUDENT_COURSE_REQUEST";
export const DELETESTUDENT_COURSE_SUCCESS = "DELETESTUDENT_COURSE_SUCCESS";
export const DELETESTUDENT_COURSE_FAIL = "DELETESTUDENT_COURSE_FAIL";
