//create stud

export const CREATE_REQUEST = "CREATE_REQUEST";
export const CREATE_SUCCESS = "CREATE_SUCCESS";
export const CREATE_FAIL = "CREATE_FAIL";

//ALL stud

export const ALLSTUDENTS_REQUEST = "ALLSTUDENTS_REQUEST";
export const ALLSTUDENTS_SUCCESS = "ALLSTUDENTS_SUCCESS";
export const ALLSTUDENTS_FAIL = "ALLSTUDENTS_FAIL";

//SINGLE VIEW

export const SINGLE_VIEW_REQUEST = "SINGLE_VIEW__REQUEST";
export const SINGLE_VIEW_SUCCESS = "SINGLE_VIEW_SUCCESS";
export const SINGLE_VIEW_FAIL = "SINGLE_VIEW_FAIL";

//DELETE stud

export const DELETE_STUDENT_REQUEST = "DELETE_STUDENT_REQUEST";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_FAIL = "DELETE_STUDENT_FAIL";

//UPDATE stud

export const UPDATE_REQUEST = "UPDATE_REQUEST";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAIL = "UPDATE_FAIL";

